swagger: '2.0'
info:
  title: "Human Services Data Meta API"
  description: "This is a complimentary API to the HSDA API focusing just on meta information."
  termsOfService: "https://openreferral.org/documentation/"
  contact:
    name: Open Referral
    url: https://openreferral.org/
    email: info@openreferral.org
  license:
    name: Open Data Commons Public Domain
    url: http://opendatacommons.org/licenses/pddl/
  version: v1.0
host: hsda.meta.api.adopta.agency
basePath: /
schemes:
  - http
produces:
  - application/json
paths:
  /meta/:
    get:
      summary: Get Meta
      description: Get Meta
      operationId: listMeta
      security:
        - appid: []
        - appkey: []
      responses:
        '200':
          description: Item Response
          schema:
            type: array
            items:
              $ref: "#/definitions/meta"
        '403':
          description: No Access Response
          schema:
            type: array
            items:
              $ref: "#/definitions/error_response"
        '500':
          description: Error Response
          schema:
            type: array
            items:
              $ref: "#/definitions/error_response"
      tags:
      - Meta
    post:
      summary: Add Meta
      description: Add Meta
      operationId: addMeta
      parameters:
        - in: body
          name: body
          schema:
            $ref: '#/definitions/meta'
      security:
        - appid: []
        - appkey: []
      responses:
        '200':
          description: Meta Response
          schema:
            type: array
            items:
              $ref: "#/definitions/meta"
        '403':
          description: No Access Response
          schema:
            type: array
            items:
              $ref: "#/definitions/error_response"
        '500':
          description: Error Response
          schema:
            type: array
            items:
              $ref: "#/definitions/error_response"
      tags:
      - Meta
  /meta/{meta_id}/:
    get:
      summary: Get Meta
      description: Get Meta
      operationId: getMeta
      parameters:
        - in: path
          required: true
          type: string
          name: meta_id
          description: 'The meta id.'
      security:
        - appid: []
        - appkey: []
      responses:
        '200':
          description: Meta Response
          schema:
            type: array
            items:
              $ref: "#/definitions/meta"
        '403':
          description: No Access Response
          schema:
            type: array
            items:
              $ref: "#/definitions/error_response"
        '500':
          description: Error Response
          schema:
            type: array
            items:
              $ref: "#/definitions/error_response"
      tags:
      - Meta
    put:
      summary: Update Meta
      description: Update an existing meta entry.
      operationId: updateMeta
      parameters:
        - in: path
          required: true
          type: string
          name: meta_id
          description: 'The meta id.'
        - in: body
          name: body
          schema:
            $ref: '#/definitions/meta'
      security:
        - appid: []
        - appkey: []
      responses:
        '200':
          description: Meta Response
          schema:
            type: array
            items:
              $ref: "#/definitions/meta"
        '403':
          description: No Access Response
          schema:
            type: array
            items:
              $ref: "#/definitions/error_response"
        '500':
          description: Error Response
          schema:
            type: array
            items:
              $ref: "#/definitions/error_response"
      tags:
      - Meta
securityDefinitions:
  appid:
    type: apiKey
    in: header
    name: x-appid
  appkey:
    type: apiKey
    in: header
    name: x-appkey
definitions:
  meta:
    properties:
      id:
        description: 'Each entry must have a unique identifier.'
        type: string
      timestamp:
        description: 'The timestamp for entry (yyyy-mm-dd)'
        type: string
      appid:
        description: 'The appid for entry.'
        type: string
      system:
        description: 'The system for entry.'
        type: string
      path:
        description: 'The path for entry.'
        type: string
      verb:
        description: 'The verb for entry.'
        type: string
      request_parameters:
        description: 'The parameters for entry.'
        type: string
      request_headers:
        description: 'The header for entry.'
        type: string
      request_body:
        description: 'The body for entry.'
        type: string
      response_body:
        description: 'The body for entry.'
        type: string
      status:
        description: 'The status of this entry (Complete, Waiting)'
        type: string
    required:
      - id
  rollback:
    properties:
      id:
        description: 'The id for the rollback.'
        type: string
  rollforward:
    properties:
      id:
        description: 'The id for the roll foward.'
        type: string
  errors:
    properties:
      id:
        description: 'The id for the errors.'
        type: string
  weblogs:
    properties:
      id:
        description: 'The id for the web logs.'
        type: string
  error_response:
    properties:
      code:
        description: 'Repeat the HTTP status code'
        type: integer
      message:
        description: 'A plain language message explaining the error'
        type: integer
